name: Update Challenge

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight (00:00) UTC
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update Challenge API
        id: trigger_update_challenge
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -H "x-scheduler-secret: e1234567890wertyuiopasdfghjklzxcvbnmewer" https://challengify.vercel.app/api/update-challenge)
          echo $RESPONSE
        
